### ISSUE TITLE
certificate broken when using CNAME to github.io

### ISSUE THREAD

**Issue by Loic-CDS** [jpawlowski/mta-sts.template#2]
Hello @jpawlowski  and thank you for your work! Forgive me if I misread the docs but I'm facing an issue after creating the CNAME record as the certificate of github.io does not match the domain.tld , any  advice on how you solved this ?
Regards

**Comment by jpawlowski** [comment]
Hey there,

You are missing the last step after the CNAME setup which is configuring the domain name as described here

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by Loic-CDS** [comment]
Thank you very much, that worked 😊

De : Julian Pawlowski ***@***.***>
Envoyé : vendredi 19 août 2022 18:14
À : jpawlowski/mta-sts.template ***@***.***>
Cc : MICHEL, Loic (COLAS DIGITAL SOLUTIONS) ***@***.***>; Author ***@***.***>
Objet : Re: [jpawlowski/mta-sts.template] certificate broken when using CNAME to github.io (Issue #2)

Message sent from Internet with ***@***.******@***.***> email address
Security warning : Do not click on the links or attachments contained in this message unless you are sure of the sender’s address.
________________________________

Hey there,

You are missing the last step after the CNAME setup which is configuring the domain name as described here

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site<https://urldefense.com/v3/__https:/docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site__;!!AixUwHL60NA!qT6N3GWnuURqj-fTj81TY9dUG0mbP1vMjtILrKzFbmCS9tqKGgVFkdw89hbtUuYettaICIhr7Y5SyrSQ1cqx3kemBS0$>

**Comment by NoSubstitute** [comment]
Maybe the bit about setting the repo up with a custom domain should be in the instructions?
Injected as a new step 4, pushing the next steps up a notch.

**Comment by jpawlowski** [comment]
@NoSubstitute, it is actually mentioned in step no.3 like this:

"... and [enable GitHub Pages](https://docs.github.com/articles/using-a-custom-domain-with-github-pages/)."
