### ISSUE TITLE
URL states 'No pages found here'

### ISSUE THREAD

**Issue by remedian** [jpawlowski/mta-sts.template#4]
I have made a cname of mta-sts.domainname.com and pointed it to my remedian.github.io.

Once I have gone to the site the text displayed is that there is no site here. Any ideas?

I have also in "Pages" added mta-sts.domainname.com as a custom domain.

Thanks

**Comment by jpawlowski** [comment]
Did you follow the instructions to enable GitHub pages for your repository?
https://docs.github.com/articles/using-a-custom-domain-with-github-pages/
